mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: Rule
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
log-level: info
ipv6: true
external-controller: :9999
external-ui: ui
secret: 
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}
sniffer: {enable: true, parse-pure-ip: true, skip-domain: [Mijia Cloud], sniff: {tls: {ports: [443, 8443]}, http: {ports: [80, 8080-8880]}, quic: {ports: [443, 8443]}}}
find-process-mode: "off"
routing-mark: 7894
dns:
  enable: true
  listen: :1053
  use-hosts: true
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.*'
  nameserver: [https://223.5.5.5/dns-query, https://doh.pub/dns-query, tls://dns.rubyfish.cn:853]
  fallback: [https://1.0.0.1/dns-query, https://8.8.4.4/dns-query, https://doh.opendns.com/dns-query]
  fallback-filter:
    geoip: true
    domain:
      - '+.bing.com'
      - '+.linkedin.com'
hosts:
   'time.android.com': 203.107.6.88
   'time.facebook.com': 203.107.6.88  
   'localhost': 127.0.0.1
proxy-groups:

- name: "AListâ™»ï¸"
  type: select
  proxies: 
  - DIRECT
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "EroticğŸ’¢"
  type: select
  proxies: 
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "LivesğŸ“º"
  type: select
  proxies: 
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "HighsğŸš§"
  type: select
  proxies: 
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "SocialğŸ’¬"
  type: select
  proxies: 
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "TikTokğŸµ"
  type: select
  proxies:
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "ProxyğŸ¯"
  type: select
  proxies: 
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "MediağŸï¸"
  type: select
  proxies: 
  - ProxyğŸ¯
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€

- name: "FInalğŸŸ"
  type: select
  proxies: 
  - ProxyğŸ¯
  - HKğŸ‡­ğŸ‡°
  - TWğŸ‡¹ğŸ‡¼
  - KRğŸ‡°ğŸ‡·
  - JPğŸ‡¯ğŸ‡µ
  - SGğŸ‡¸ğŸ‡¬
  - USğŸ‡ºğŸ‡¸
  - OTğŸŒ€ 
  - DIRECT

- name: "HKğŸ‡­ğŸ‡°"
  type: select
  filter: "ğŸ‡­ğŸ‡°|é¦™æ¸¯|æ¸¯|HK"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "TWğŸ‡¹ğŸ‡¼"
  type: select
  filter: "ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|å°æ¹¾|TW"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "KRğŸ‡°ğŸ‡·"
  type: select
  filter: "ğŸ‡°ğŸ‡·|éŸ©å›½|KR"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "JPğŸ‡¯ğŸ‡µ"
  type: select
  filter: "ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "SGğŸ‡¸ğŸ‡¬"
  type: select
  filter: "ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "USğŸ‡ºğŸ‡¸"
  type: select
  filter: "ğŸ‡ºğŸ‡¸|ç¾å›½|US"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

- name: "OTğŸŒ€"
  type: select
  exclude-filter: "Traffic|Expire|å‰©ä½™|ğŸ‡­ğŸ‡°|é¦™æ¸¯|æ¸¯|HK|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|å°æ¹¾|TW|ğŸ‡°ğŸ‡·|éŸ©å›½|KR|ğŸ‡¯ğŸ‡µ|æ—¥|JP|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|ğŸ‡ºğŸ‡¸|ç¾å›½|US"
  use:
  - YtooğŸ”°
  - BestğŸ’
  - é­”æˆ’ğŸ’«
  - ç¥å™¨ğŸ”¶
  - å›½é™…ğŸš
  - æœé…±ğŸ¥¥
  - å¿«è·‘ğŸƒ

proxy-providers:
  YtooğŸ”°:
    type: http
    url: "https://api.stentvessel.top/sub?target=clash&clash.doh=true&emoji=true&scv=true&udp=true&new_name=true&filename=YToo_Trojan&url=https%3A%2F%2Fapi.ytoo.xyz%2Fosubscribe.php%3Fsid%3D67918%26token%3D7nVZOnkQQH0G"
    path: ./proxy_providers/Ytoo.yaml
    interval: 21600
    filter: "Traffic|Expire|0.2|æ ‡å‡†|é«˜çº§"
    override:
      additional-prefix: "ğŸ”°"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

  BestğŸ’:
    type: http
    url: "https://rcvws73c.pronetwork.top:8443/api/v1/client/ae0cef29f96f4c1d157946d6cbc5d5fc?flag=clashmeta"
    path: ./proxy_providers/BestVPN.yaml
    interval: 21600
    exclude-filter: "ç½‘å€|è‡ªåŠ¨|iOSä¼˜åŒ–|æ–°åè®®"
    override:
      additional-prefix: "ğŸ’"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


  é­”æˆ’ğŸ’«:
    type: http
    url: "https://mojie0201.xn--8stx8olrwkucjq3b.com/api/v1/client/subscribe?token=8c50ea1fa879acf182f2ea21014ba8f3"
    path: ./proxy_providers/Mojie.yaml
    interval: 21600
    exclude-filter: "å®˜ç½‘|è‡ªåŠ¨|å¥—é¤|è¿‡æ»¤"
    override:
      additional-prefix: "ğŸ’«"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


  ç¥å™¨ğŸ”¶:
    type: http
    url: "https://sub.imtp.eu.org/api/v1/client/subscribe?token=700fd6d4ae7cbaa395724f0dbb53679b&flag=meta&types=all"
    path: ./proxy_providers/Yydsvpn.yaml
    interval: 21600
    exclude-filter: "å¥—é¤|shenseven|âœ°âœ°|â˜…â˜…"
    override:
      additional-prefix: "ğŸ”¶"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


  å›½é™…ğŸš:
    type: http
    url: "https://xtls.rprx.vision/api/v1/client/subscribe?token=c39da53d11c4590673c7cb825929acf8"
    path: ./proxy_providers/Guoji.yaml
    interval: 21600
    exclude-filter: "å®˜ç½‘|ç¦æ­¢|å›½å†…|ç”µä¿¡|è”é€š|ç§»åŠ¨|å›½é™…"
    override:
      additional-prefix: "ğŸš"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


  æœé…±ğŸ¥¥:
    type: http
    url: "https://sub.jamjam.dev/api/v1/client/subscribe?token=8a4693656e0935d5ad12d8d7a138d845"
    path: ./proxy_providers/Jiguo.yaml
    interval: 21600
    exclude-filter: "å®˜ç½‘|è‡ªåŠ¨|ç”µä¿¡|è”é€š|ç§»åŠ¨"
    override:
      additional-prefix: "ğŸ¥¥"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


  å¿«è·‘ğŸƒ:
    type: http
    url: "https://kpjc.kuaipao.us.kg/api/v1/client/subscribe?token=af87c5687f045b4035e632611e8becb4"
    path: ./proxy_providers/Kuapa.yaml
    interval: 21600
    filter: "(?=.*(å‰©ä½™|x1))^((?!(CN|x15)).)*$"
    override:
      additional-prefix: "ğŸƒ"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300



rules:
 - RULE-SET,Aroce,DIRECT

 - RULE-SET,Pikpak,AListâ™»ï¸

 - RULE-SET,Erotic,EroticğŸ’¢

 - RULE-SET,Lives,LivesğŸ“º

 - RULE-SET,Highs,HighsğŸš§

 - RULE-SET,Telegram,SocialğŸ’¬

 - RULE-SET,TikTok,TikTokğŸµ

 - RULE-SET,Youtube,MediağŸï¸

 - RULE-SET,Proxy,ProxyğŸ¯

 - GEOIP,CN,DIRECT
 - GEOSITE,CN,DIRECT

 - MATCH,FInalğŸŸ
rule-providers:
  Aroce:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/zhangruxianga/proxy/refs/heads/master/clash/Aroce.yaml
    path: ./rule_provider/Aroce.yaml
    interval: 86400

  Erotic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/zhangruxianga/proxy/refs/heads/master/clash/Erotic.yaml
    path: ./rule_provider/Erotic.yaml
    interval: 86400

  Lives:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/zhangruxianga/proxy/refs/heads/master/clash/Lives.yaml
    path: ./rule_provider/Lives.yaml
    interval: 86400

  Highs:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/zhangruxianga/proxy/refs/heads/master/clash/Highs.yaml
    path: ./rule_provider/Highs.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    path: ./rule_provider/Telegram.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./rule_provider/Proxy.yaml
    interval: 86400

  Pikpak:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PikPak/PikPak.yaml
    path: ./rule_provider/Pikpak.yaml
    interval: 86400

  TikTok:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml
    path: ./rule_provider/TikTok.yaml
    interval: 86400

  Youtube:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    path: ./rule_provider/Youtube.yaml
    interval: 86400